// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCatLzdaukkGeJaF4tThifZ53DwIW_lbbw',
    appId: '1:869564313429:web:488b53879d64ba31c189dc',
    messagingSenderId: '869564313429',
    projectId: 'fir-58f6c',
    authDomain: 'fir-58f6c.firebaseapp.com',
    storageBucket: 'fir-58f6c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1KHsgY1IpQxcns1LANmTNqEMxyNKG5Xg',
    appId: '1:869564313429:android:33ded5317ed67aa1c189dc',
    messagingSenderId: '869564313429',
    projectId: 'fir-58f6c',
    storageBucket: 'fir-58f6c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9VRzwPbYC5MboGX3NmLOVu7dzJJmqzGo',
    appId: '1:869564313429:ios:f44c6443b83cceacc189dc',
    messagingSenderId: '869564313429',
    projectId: 'fir-58f6c',
    storageBucket: 'fir-58f6c.firebasestorage.app',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9VRzwPbYC5MboGX3NmLOVu7dzJJmqzGo',
    appId: '1:869564313429:ios:f44c6443b83cceacc189dc',
    messagingSenderId: '869564313429',
    projectId: 'fir-58f6c',
    storageBucket: 'fir-58f6c.firebasestorage.app',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCatLzdaukkGeJaF4tThifZ53DwIW_lbbw',
    appId: '1:869564313429:web:ab0ad525af24a163c189dc',
    messagingSenderId: '869564313429',
    projectId: 'fir-58f6c',
    authDomain: 'fir-58f6c.firebaseapp.com',
    storageBucket: 'fir-58f6c.firebasestorage.app',
  );
}
